#!/usr/bin/env python3
"""Export one seamless loader cycle for the browser and native video player."""
import json
import pathlib
import re
import subprocess

root = pathlib.Path(__file__).resolve().parents[1]
source = (root / 'scripts/splash.sh').read_text()
source = source.replace('exec >"$TTY" 2>/dev/null || exit 0', ':')
source = source.replace('if size=$(stty size <"$TTY" 2>/dev/null); then', 'if false; then')
source = source.replace('printf \'%s\' "$FRAME"', 'printf \'%s\\0\' "$FRAME"')
source = source.replace('[[ ${SPLASH_FAST:-0} == 1 ]] && sleep 0.01 || sleep "$1"', 'printf \'%s\\0\' "$1"')
result = subprocess.run(['bash', '-s', '--', '--once'], input=source, text=True,
                        capture_output=True, check=True)
parts = result.stdout.split('\0')
parts[0] = parts[0].split('\x1b[?25l', 1)[1]
frames = [[parts[i], float(parts[i + 1])] for i in range(0, len(parts) - 2, 2)]
assert len(frames) > 50
final = parts[-2]
assert any(frame[0] == final for frame in frames)
(root / 'scripts/kiosk-ext/splash-frames.js').write_text(
    '// Generated from scripts/splash.sh by tools/build-splash-frames.py.\n'
    'globalThis.crtSplashFrames = ' + json.dumps(frames, ensure_ascii=False, separators=(',', ':')) + ';\n'
    'globalThis.crtSplashFinal = ' + json.dumps(final, ensure_ascii=False) + ';\n')

# Matching monochrome station card for X while Chromium opens its window.
bits = bytearray(720 * 480 // 8)
row = col = 0
for token in re.finditer(r'\x1b\[([?\d;]*)([A-Za-z])|([^\x1b]+)', final):
    if token[2] == 'H':
        coords = [int(v or 1) for v in token[1].split(';')]
        row, col = coords[0] - 1, (coords[1] if len(coords) > 1 else 1) - 1
    elif token[3]:
        for char in token[3]:
            x, y = col * 8, row * 16
            col += 1
            start, end = {'█': (0, 16), '▀': (0, 8), '▄': (8, 16), '■': (4, 12)}.get(char, (0, 0))
            for yy in range(y + start, y + end):
                if 0 <= x < 720 and 0 <= yy < 480:
                    bits[yy * 90 + x // 8] = 255
(root / 'scripts/kiosk-ext/boot-card.xbm').write_text(
    '#define boot_card_width 720\n#define boot_card_height 480\n'
    'static unsigned char boot_card_bits[] = {\n' +
    ',\n'.join(','.join(f'0x{b:02x}' for b in bits[i:i+30]) for i in range(0, len(bits), 30)) + '\n};\n')

# Font-independent ASS polygons: the native loader uses exactly the console pixels.
def ass_frame(ansi):
    row = col = 0
    bold, color = False, 7
    palette = ['000000', '0000AA', '00AA00', '0055AA', 'AA0000', 'AA00AA', 'AAAA00', 'AAAAAA']
    bright = ['555555', '5555FF', '55FF55', '55FFFF', 'FF5555', 'FF55FF', 'FFFF55', 'FFFFFF']
    paths = {'000000': ['m 0 0 l 720 0 720 480 0 480']}
    for token in re.finditer(r'\x1b\[([?\d;]*)([A-Za-z])|([^\x1b]+)', ansi):
        if token[2] == 'H':
            coords = [int(v or 1) for v in token[1].split(';')]
            row, col = coords[0] - 1, (coords[1] if len(coords) > 1 else 1) - 1
        elif token[2] == 'm':
            for code in map(int, token[1].split(';')):
                if code == 0: bold, color = False, 7
                elif code == 1: bold = True
                elif 30 <= code <= 37: color = code - 30
        elif token[3]:
            for char in token[3]:
                x, y = col * 8, row * 16
                col += 1
                start, end = {'█': (0, 16), '▀': (0, 8), '▄': (8, 16)}.get(char, (0, 0))
                if start == end: continue
                c = (bright if bold else palette)[color]
                paths.setdefault(c, []).append(f'm {x} {y+start} l {x+8} {y+start} {x+8} {y+end} {x} {y+end}')
    return '\n'.join('{\\an7\\pos(0,0)\\bord0\\shad0\\1c&H'+c+'&\\p1}'+ ' '.join(p) for c,p in paths.items())
(root / 'scripts/startup/frames.lua').write_text(
    '-- Generated by tools/build-splash-frames.py; font-independent loading frames.\nreturn {\n' +
    ',\n'.join(json.dumps(ass_frame(frame[0])) for frame in frames) + '\n}\n')
